rawdata:
    ## rawdata/04.rna-seq/{sample}.R1.fastq.gz
    RNA:
        - "potato_leaf"

## rawdata/05.iso-seq/{sample}.subreads.bam
    ISO:

name : "DM"
outdir: "/work/home/zhangzhiyang/project/HHS_potato/01.annotation/Annotation/pipeline"  

parameters:
    EDTA:
        ## final step [all,filter,final,anno]
        step: "all"
        ## rice,maize,others
        species: "others"
        sensitive: 0
        ## maize corrected TE lib
        lib:
        cds:
        # lib: "maizeTE02052020"
        # cds: "Zea_mays.B73_RefGen_v4.cdna.all.fa"



########   software and script   ########
biosoft:
    env:
        module: "module use /work/home/zhangzhiyang/software/modulefiles && module purge"
        mf: "module use /work/home/zhangzhiyang/software/modulefiles"
        mp: "module purge"
        singularity: "module load singularity/3.8.7"
        asm: "module load asm/1.0"
    repeat:
        EDTA: "module load EDTA/1.9.4"
    braker:
        braker2: "module load braker3/2.1.5"
        #braker2: "module load braker2/2.1.5"
        mapping: "module load mapping/1.0"
        #QC: "source /public/home/baozhigui/miniconda3/bin/activate QC"
        QC: "module load QC/1.0"
        genemark: "module load GeneMark-ES/4.3.8"
        augustus_conf: "config/"
    maker:
        maker2: "module load maker/2.31.11"

# #######################    busco db    ########################
